### ISSUE TITLE
jwplayer with Recyclerview

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [jwplayer/jwplayer-android-best-practice-apps#8]
how to run this sample with RecyclerView instead of listview ?

**Comment by RikHeijdens** [comment]
You will have to replace the ListView defined in the [layout file](https://github.com/jwplayer/jwplayer-android-best-practice-apps/blob/master/listview-fullscreen/app/src/main/res/layout/content_main.xml#L8) with a RecyclerView. Afterwards you'll need to populate that RecyclerView with data using an adapter. This project contains an adapter that works for a ListView, you might have to modify it in order to make it work for a RecyclerView.

Please refer to the training on [developer.android.com](https://developer.android.com/training/material/lists-cards.html) on how to implement a RecyclerView.

**Comment by AlirezaGhanbarinia** [comment]
when Intial  jwplayer In recyclerview ,  If we scroll recyclerview, while jwplayer is playing , Jwplayer will be crashed. I used from this sample code for making this recycle sample.
I couldn't make this sample for recyclerview. Please help me.
And one another question :
How Do I play only one video at once and stop other videos in recycler view?

**Comment by AlirezaGhanbarinia** [comment]
There is some problems in this sample.
1-while the video is playing , If we scroll ,the following Items become initialed and stoped randomly ( the problem stands for listview position.)
2-I want to don't be played more that one video at once but in this sample happen this case.

**Comment by jemshit** [comment]
recyclerView sample is important since it is used frequently than listView

**Comment by GMSyrimis** [comment]
Closing this thread as we now have a RecyclerView demo as part of this repo
